spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fridgeStorage?useSSL=false
    username: root
    password: 'Admin@123'
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect

#JPA Settings