name: CI Pipeline - Build, Test, Validate Commits and Release

on:
  push:
    branches: [main] # Este workflow será executado em pushes para a branch 'main'
  pull_request:
    branches: [main] # Será executado no Pull Request

jobs:
  # Esse job executa para so aceitar caso ele build e teste corretamente
  build-application:
    name: Build and Test Spring Boot Application Fridge Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./fridgeApi
        run: mvn -B verify

  # Esse job valida os commits para ver se é semantico ou não
  validate-commits:
    name: Validate Conventional Commits
    runs-on: ubuntu-latest
    needs: build-application # Este job só roda se 'build-and-test' for bem-sucedido
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para ler o histórico de commits

      - name: Validate Conventional Commit
        uses: wagoid/commitlint-github-action@v5

  # Esse job instala as dependecias necessarias para validar os commits
  semantic-release:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate-commits # Este job só roda se a validação de commits passar
    permissions:
      contents: write # Permitir criar release and push tags
      issues: write # Permitir criar issues e falhas
      pull-requests: write # Permitir comentar commits
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Semantic Release dependencies
        run: npm install semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/git @semantic-release/github

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
